<?php
namespace Contain\Entity\Form;

use Zend\Form;

/**
 * Setting Form (auto-generated by the Contain module)
 *
 * This instance should not be edited directly. Edit the definition file instead
 * and recompile.
 */
class Setting extends Form\Form
{
    /**
     * Creates form fields for each of the entity properties.
     *
     * @return  $this
     */
    public function __construct()
    {
        parent::__construct('Setting');
        $this->setInputFilter(new Contain\Entity\Filter\Setting());

        $factory = new Form\Factory();

        $this->add($factory->createElement(array(
            'name' => 'name',
            'type' => 'Zend\\Form\\Element\\Text',
            'options' => array (
  'label' => 'Name',
),
            'attributes' => array (
),
        )));

        $this->add($factory->createElement(array(
            'name' => 'value',
            'type' => 'Zend\\Form\\Element\\Text',
            'options' => array (
  'label' => 'Value',
),
            'attributes' => array (
),
        )));

    }
}
