<?php
namespace Contain\Entity\Form;

/**
 * Settings Form (auto-generated by the Contain module)
 *
 * This instance should not be edited directly. Edit the definition file instead
 * and recompile.
 */
class Settings extends \Zend\Form\Form
{
    /**
     * Creates form fields for each of the entity properties.
     *
     * @return  $this
     */
    public function __construct()
    {
        parent::__construct('Settings');
        $this->setInputFilter(new \Contain\Entity\Filter\Settings());

        $factory = new \Zend\Form\Factory();

    }
}
