<?php echo '<?php'; ?>

namespace <?php echo $this->namespace; ?>;

/**
 * <?php echo $this->name; ?> Form (auto-generated by the Contain module)
 *
 * This instance should not be edited directly. Edit the definition file instead
 * and recompile.
 */
class <?php echo $this->name; ?> extends \Zend\Form\Form
{
    /**
     * Creates form fields for each of the entity properties.
     *
     * @return  $this
     */
    public function __construct()
    {
        parent::__construct('<?php echo $this->name; ?>');
<?php if ($this->filter): ?>
        $this->setInputFilter(new \<?php echo $this->filter; ?>());

<?php endif; ?>
        $factory = new \Zend\Form\Factory();

