<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Contain\Module'                               => __DIR__ . '/Module.php',
    'Contain\Exception\RuntimeException'           => __DIR__ . '/src/Contain/Entity/Exception/RuntimeException.php',
    'Contain\Exception\InvalidArgumentException'   => __DIR__ . '/src/Contain/Entity/Exception/InvalidArgumentException.php',
    'Contain\Entity\Property\Property'             => __DIR__ . '/src/Contain/Entity/Property/Property.php',
    'Contain\Entity\Property\Type\IntegerType'     => __DIR__ . '/src/Contain/Entity/Property/Type/IntegerType.php',
    'Contain\Entity\Property\Type\EnumType'        => __DIR__ . '/src/Contain/Entity/Property/Type/EnumType.php',
    'Contain\Entity\Property\Type\TypeInterface'   => __DIR__ . '/src/Contain/Entity/Property/Type/TypeInterface.php',
    'Contain\Entity\Property\Type\ListType'        => __DIR__ . '/src/Contain/Entity/Property/Type/ListType.php',
    'Contain\Entity\Property\Type\DateTimeType'    => __DIR__ . '/src/Contain/Entity/Property/Type/DateTimeType.php',
    'Contain\Entity\Property\Type\StringType'      => __DIR__ . '/src/Contain/Entity/Property/Type/StringType.php',
    'Contain\Entity\Property\Type\DoubleType'      => __DIR__ . '/src/Contain/Entity/Property/Type/DoubleType.php',
    'Contain\Entity\Property\Type\BooleanType'     => __DIR__ . '/src/Contain/Entity/Property/Type/BooleanType.php',
    'Contain\Entity\Definition\AbstractDefinition' => __DIR__ . '/src/Contain/Entity/Definition/AbstractDefinition.php',
    'Contain\Entity\Definition\Timestampable'      => __DIR__ . '/src/Contain/Entity/Definition/Timestampable.php',
    'Contain\Entity\Definition\User'               => __DIR__ . '/src/Contain/Entity/Definition/User.php',
    'Contain\Entity\User'                          => __DIR__ . '/src/Contain/Entity/UserMe.php',
    'Contain\Entity\Compiler\Compiler'             => __DIR__ . '/src/Contain/Entity/Compiler/Compiler.php',
);