<?php
namespace \var\www\platform\vendor\contain\contain\src\Contain\Entity;

use Contain\Entity\AbstractEntity;
use Contain\Entity\Property\Property;
use Zend\EventManager\Event;
use Zend\EventManager\EventManager;

/**
 * Setting Entity (auto-generated by the Contain module)
 *
 * This instance should not be edited directly. Edit the definition file instead 
 * and recompile.
 */
class Setting extends AbstractEntity
{
    /**
     * Initializes the properties of this entity.
     *
     * @return  $this
     */
    public function init()
    {
        $this->properties['name'] = new Property('\Contain\Entity\Property\Type\StringType', array (
  'required' => true,
));
        $this->properties['value'] = new Property('\Contain\Entity\Property\Type\MixedType');
            }

}
