#!/usr/bin/env php
<?php
/**
 * Contain Project
 *
 * @note This needs to be rewritten to be more portable. This is a 
 * work in progress.
 *
 * This source file is subject to the BSD license bundled with
 * this package in the LICENSE.txt file. It is also available
 * on the world-wide-web at http://www.opensource.org/licenses/bsd-license.php.
 * If you are unable to receive a copy of the license or have 
 * questions concerning the terms, please send an email to
 * me@andrewkandels.com.
 *
 * @category    akandels
 * @package     contain
 * @author      Andrew Kandels (me@andrewkandels.com)
 * @copyright   Copyright (c) 2012 Andrew P. Kandels (http://andrewkandels.com)
 * @license     http://www.opensource.org/licenses/bsd-license.php BSD License
 * @link        http://andrewkandels.com/contain
 */

use Zend\ServiceManager\ServiceManager;
use Zend\Mvc\Service\ServiceManagerConfiguration;

if (empty($argv[1])) {
    fprintf(STDERR, "Syntax: compile FULL_ENTITY_NAMESPACE\n");
    exit(1);
}

ini_set('display_errors', 1);
ini_set('log_errors', 1);
error_reporting(E_ALL);
chdir(__DIR__ . '/../../../..');

require_once('./vendor/autoload.php');

$configuration = include './config/application.config.php';
$serviceManager = new ServiceManager(new ServiceManagerConfiguration($configuration['service_manager']));
$serviceManager->setService('ApplicationConfiguration', $configuration);
$serviceManager->get('ModuleManager')->loadModules();

$compiler = $serviceManager->get('di')->get('Contain\Entity\Compiler\Compiler');
try {
    $compiler->compile($argv[1]);
} catch (Exception $e) {
    fprintf(STDERR, "Exception: %s\n--\n%s\n\n", $e->getMessage(), $e->getTraceAsString());
    exit(1);
}

exit(0);
