#!/usr/bin/env php
<?php
/**
 * Contain Project
 *
 * Generates a ZF2 classmap for all contain classes.
 *
 * This source file is subject to the BSD license bundled with
 * this package in the LICENSE.txt file. It is also available
 * on the world-wide-web at http://www.opensource.org/licenses/bsd-license.php.
 * If you are unable to receive a copy of the license or have
 * questions concerning the terms, please send an email to
 * me@andrewkandels.com.
 *
 * @category    akandels
 * @package     contain
 * @author      Andrew Kandels (me@andrewkandels.com)
 * @copyright   Copyright (c) 2012 Andrew P. Kandels (http://andrewkandels.com)
 * @license     http://www.opensource.org/licenses/bsd-license.php BSD License
 * @link        http://andrewkandels.com/contain
 */

require_once(__DIR__ . '/abstract-script.php');

passthru(sprintf('%s %s/bin/classmap_generator.php --library %s',
    escapeshellcmd(trim(`which php`)),
    escapeshellarg(ZF2_FRAMEWORK_PATH),
    escapeshellarg(CONTAIN_PATH)
));
